/*
 Copyright (c) 2020-2022 Dell Inc. or its subsidiaries. All Rights Reserved.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

     http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
*/

// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/dell/karavi-topology/internal/service (interfaces: VolumeInfoGetter)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	k8s "github.com/dell/karavi-topology/internal/k8s"
	gomock "github.com/golang/mock/gomock"
)

// MockVolumeInfoGetter is a mock of VolumeInfoGetter interface.
type MockVolumeInfoGetter struct {
	ctrl     *gomock.Controller
	recorder *MockVolumeInfoGetterMockRecorder
}

// MockVolumeInfoGetterMockRecorder is the mock recorder for MockVolumeInfoGetter.
type MockVolumeInfoGetterMockRecorder struct {
	mock *MockVolumeInfoGetter
}

// NewMockVolumeInfoGetter creates a new mock instance.
func NewMockVolumeInfoGetter(ctrl *gomock.Controller) *MockVolumeInfoGetter {
	mock := &MockVolumeInfoGetter{ctrl: ctrl}
	mock.recorder = &MockVolumeInfoGetterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVolumeInfoGetter) EXPECT() *MockVolumeInfoGetterMockRecorder {
	return m.recorder
}

// GetPersistentVolumes mocks base method.
func (m *MockVolumeInfoGetter) GetPersistentVolumes(arg0 context.Context) ([]k8s.VolumeInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPersistentVolumes", arg0)
	ret0, _ := ret[0].([]k8s.VolumeInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPersistentVolumes indicates an expected call of GetPersistentVolumes.
func (mr *MockVolumeInfoGetterMockRecorder) GetPersistentVolumes(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPersistentVolumes", reflect.TypeOf((*MockVolumeInfoGetter)(nil).GetPersistentVolumes), arg0)
}
